version: '3'

services:
  boost_test:
    build: ./vendor/boost/
    image: denley/boost
    working_dir: /opt/app
    entrypoint: /opt/app/docker-entrypoint.sh
    volumes:
      - .:/opt/app
      - ./src:/opt/app/src/
